Use new recordIssue: API
google/google-toolbox-for-mac pull request #315
Opened 2022-02-14 16:41 UTC by eytanbiala

-[XCTestCase recordFailureWithDescription:inFile:atLine:expected:] is deprecated, and the replacement is recordIssue:

2022-02-22 16:51 UTC, dmaclach commented on UnitTesting/GTMGoogleTestRunner.mm
>  #if IS_XCODE_11_4_OR_BETTER
I believe XCTIssue came in with Xcode 12? Do we need yet another #if here to cover all the cases?

2022-03-06 14:58 UTC, eytanbiala commented on UnitTesting/GTMGoogleTestRunner.mm
>  #if IS_XCODE_11_4_OR_BETTER
Yes that's right, good catch! Updated but I could not test with Xcode < 12 as it's no longer supported on Monterey

2022-04-22 04:35 UTC, gracemerry approved these changes

2022-04-22 19:25 UTC, dmaclach requested changes
Apologies for being slow on this. I totally missed it.

2022-04-22 19:25 UTC, dmaclach commented on UnitTesting/GTMGoogleTestRunner.mm
>        NSString *file = @(file_name ? file_name : "<file name unavailable>");
Can we fix the indent here?

2022-04-22 19:25 UTC, dmaclach commented on UnitTesting/GTMGoogleTestRunner.mm
> +      XCTSourceCodeLocation *location = [[XCTSourceCodeLocation alloc] initWithFilePath:file lineNumber:line];
Please make this wrap appropriately. I believe this code is 80 col.

2022-04-23 23:47 UTC, eytanbiala commented on UnitTesting/GTMGoogleTestRunner.mm
>        NSString *file = @(file_name ? file_name : "<file name unavailable>");
Done

2022-04-23 23:59 UTC, eytanbiala reviewed
Thanks for coming back to it, I forgot about it as well :) (next time can send a private CL if that's preferred)

2022-04-25 16:44 UTC, dmaclach approved these changes
Thanks! LGTM

2022-04-25 16:52 UTC, merged